project_id = "ofolgjtqgmudfeoppwtb"

[functions.create-user]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.send-os-email]
verify_jwt = false

[functions.check-overdue-agendas]
verify_jwt = false

[functions.protheus-users]
verify_jwt = false

[functions.monday-sync-project]
verify_jwt = false

[functions.monday-reset-board]
verify_jwt = false

[functions.sharepoint-upload]
verify_jwt = false

[functions.check-alertas]
verify_jwt = false

[functions.autentique-send]
verify_jwt = false

[functions.monday-agenda-sync]
verify_jwt = false

[functions.monthly-expenses-scheduler]
verify_jwt = false

[functions.agendas-maintenance]
verify_jwt = false
